name: Deploy content
on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-deploy]
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
          cache: 'pip'
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: ~/.cache
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force
